import { RouteNames, Routes } from '@/interfaces/global';
import type { IErrorTableCell } from '@/interfaces/errorTable';

export const appLinks = [
  { url: Routes.HOME, title: RouteNames.HOME },
  { url: Routes.ABOUT, title: RouteNames.ABOUT },
  { url: Routes.SKILLS, title: RouteNames.SKILLS },
  { url: Routes.PORTFOLIO, title: RouteNames.PORTFOLIO },
  { url: Routes.CONTACT, title: RouteNames.CONTACT },
  { url: Routes.HELP, title: RouteNames.HELP },
];

export const errorTable: IErrorTableCell[] = [
  { letter: 'k' },
  { letter: 'v' },
  { letter: 'n' },
  { letter: 'z' },
  { letter: 'i' },
  { letter: 'x' },
  { letter: 'm' },
  { letter: 'e' },
  { letter: 't' },
  { letter: 'a' },
  { letter: 'x' },
  { letter: 'l' },
  { letter: '4', class: 'word' },
  { letter: '0', class: 'word' },
  { letter: '4', class: 'word' },
  { letter: 'y' },
  { letter: 'y' },
  { letter: 'w' },
  { letter: 'v' },
  { letter: 'b' },
  { letter: 'o' },
  { letter: 'q' },
  { letter: 'd' },
  { letter: 'y' },
  { letter: 'p' },
  { letter: 'a' },
  { letter: 'p', class: 'word' },
  { letter: 'a', class: 'word' },
  { letter: 'g', class: 'word' },
  { letter: 'e', class: 'word' },
  { letter: 'v' },
  { letter: 'j' },
  { letter: 'a' },
  { letter: 'n', class: 'word' },
  { letter: 'o', class: 'word' },
  { letter: 't', class: 'word' },
  { letter: 's' },
  { letter: 'c' },
  { letter: 'e' },
  { letter: 'w' },
  { letter: 'v' },
  { letter: 'x' },
  { letter: 'e' },
  { letter: 'p' },
  { letter: 'c' },
  { letter: 'f' },
  { letter: 'h' },
  { letter: 'q' },
  { letter: 'e' },
  { letter: 'f', class: 'word' },
  { letter: 'o', class: 'word' },
  { letter: 'u', class: 'word' },
  { letter: 'n', class: 'word' },
  { letter: 'd', class: 'word' },
  { letter: 's' },
  { letter: 'w' },
  { letter: 'q' },
  { letter: 'v' },
  { letter: 'o' },
  { letter: 's' },
  { letter: 'm' },
  { letter: 'v' },
  { letter: 'f' },
  { letter: 'u' },
];
